apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: arcadia
spec:
  host: adcf6a4d989e34a2eac0ecbb4aca9520-1726245923.eu-west-1.elb.amazonaws.com  
  tls: 
   secret: arcadia-wildcard
   redirect:
        enable: true
  upstreams:
    - name: arcadia-users
      service: arcadia-users
      port: 80
      healthCheck:
              enable: true
              path: /healthz
    - name: arcadia-login
      service: arcadia-login
      port: 80
      healthCheck:
              enable: true
              path: /healthz
    - name: arcadia-stocks
      service: arcadia-stocks
      port: 80
      healthCheck:
              enable: true
              path: /healthz
    - name: arcadia-stock-transaction
      service: arcadia-stock-transaction
      port: 80
      healthCheck:
              enable: true
              path: /healthz
    - name: arcadia-frontend
      service: arcadia-frontend
      port: 80
      healthCheck:
              enable: true
              path: /healthz
  routes:
    - path: /v1/user      
      action:
        pass: arcadia-users
    - path: /v1/login      
      action:
        pass: arcadia-login
    - path: /v1/stock      
      action:
        pass: arcadia-stocks
    - path: /v1/stockt      
      action:
        pass: arcadia-stock-transaction
    - path: /      
      action:
        pass: arcadia-frontend
